# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - stocks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release
      
      - name: Publish Web App
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp-artifacts
          path: ./publish
          retention-days: 5
#      - uses: actions/checkout@v4
#
#      - name: Set up .NET Core
#        uses: actions/setup-dotnet@v4
#        with:
#          dotnet-version: '9.x'
#
#      - name: Build with dotnet
#        run: dotnet build --configuration Release
#
#      - name: dotnet publish
#        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
#
#      - name: Upload artifact for deployment job
#        uses: actions/upload-artifact@v4
#        with:
#          name: .net-app
#          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp-artifacts
          path: drop

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_065331C904DA48C3B9E5EF7DC0F34417 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A46C94B229A240D8822C10522797D43C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE543C61A81A4DC4B4BF21CFD53FAD04 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        if: success()
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stocks'
          package: drop
          